version: "3.9"
services:
  backend:
    build:
      context: .
      dockerfile: Docker/Dockerfile.backend
    env_file: .env
    environment:
      - CORS_ALLOWED_ORIGINS=http://localhost:5173
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"

  frontend:
    build:
      context: .
      dockerfile: Docker/Dockerfile.frontend
    volumes:
      - ./frontend:/app/frontend
      - /app/frontend/node_modules
    working_dir: /app/frontend
    environment:
      - CHOKIDAR_USEPOLLING=1
      - WATCHPACK_POLLING=true
      - VITE_HMR_HOST=localhost
      - VITE_HMR_PORT=5173
    command: ["sh", "-c", "npm install && npm run dev"]
    ports:
      - "5173:5173"
    depends_on:
      - backend

  db:
    image: postgres:15
    restart: always
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-postgres}"]
      interval: 5s
      timeout: 5s
      retries: 10

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  postgres_data: